-- LocalFix Database Schema for Users
-- Save as: database/migrations/001_create_users_table.sql

CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone VARCHAR2(11) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    user_type VARCHAR2(20) CHECK (user_type IN ('citizen', 'worker', 'admin')) NOT NULL,
    status VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Keep only the index on user_type
CREATE INDEX idx_users_type ON users(user_type);

-- Trigger for auto-updating updated_at
CREATE OR REPLACE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
-- 👆 No slash here for DBeaver/SQLTools

-- Insert default admin user
INSERT INTO users (name, email, phone, address, password, user_type) 
VALUES (
    'Admin User',
    'admin@localfix.com',
    '01700000000',
    'System Admin',
    '$2a$10$KIXqXQxvS7/X5CJGqQqGr.vQrY5qR5qR5qR5qR5qR5qR5qR5qR5qR5q',
    'admin'
);

COMMIT;
