-- LocalFix Database Schema for Locations
-- Save as: database/migrations/002_create_locations_table.sql

CREATE TABLE locations (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upazila VARCHAR2(50) NOT NULL,
    district VARCHAR2(50) NOT NULL,
    full_address VARCHAR2(500) NOT NULL,
    latitude NUMBER(10,8),
    longitude NUMBER(11,8),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for location searches
CREATE INDEX idx_locations_district ON locations(district);
CREATE INDEX idx_locations_upazila ON locations(upazila);

-- Insert some sample locations
INSERT INTO locations (upazila, district, full_address, latitude, longitude) VALUES
('Dhanmondi', 'Dhaka', 'Dhanmondi, Dhaka-1205', 23.7461, 90.3742);

INSERT INTO locations (upazila, district, full_address, latitude, longitude) VALUES
('Gulshan', 'Dhaka', 'Gulshan, Dhaka-1212', 23.7806, 90.4193);

INSERT INTO locations (upazila, district, full_address, latitude, longitude) VALUES
('Uttara', 'Dhaka', 'Uttara, Dhaka-1230', 23.8759, 90.3795);

COMMIT;