
CREATE TABLE locations (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upazila VARCHAR2(50) NOT NULL,
    district VARCHAR2(50) NOT NULL,
    full_address VARCHAR2(500) NOT NULL,
    latitude NUMBER(10,8),
    longitude NUMBER(11,8),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for location searches
CREATE INDEX idx_locations_district ON locations(district);
CREATE INDEX idx_locations_upazila ON locations(upazila);

COMMIT;