-- LocalFix Database Schema for Issues
-- Save as: database/migrations/003_create_issues_table.sql

CREATE TABLE issues (
    issue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_category VARCHAR2(50) NOT NULL,
    issue_name VARCHAR2(100) NOT NULL,
    description CLOB,
    priority VARCHAR2(20) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for category searches
CREATE INDEX idx_issues_category ON issues(issue_category);
CREATE INDEX idx_issues_priority ON issues(priority);

-- Trigger for auto-updating updated_at
CREATE OR REPLACE TRIGGER trg_issues_updated_at
    BEFORE UPDATE ON issues
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;

-- Insert sample issue categories
INSERT INTO issues (issue_category, issue_name, description, priority) VALUES
('Road & Infrastructure', 'Broken Road', 'Road damage that needs repair', 'high');

INSERT INTO issues (issue_category, issue_name, description, priority) VALUES
('Electricity & Street Lights', 'Street Light Not Working', 'Non-functional street lighting', 'medium');

INSERT INTO issues (issue_category, issue_name, description, priority) VALUES
('Water & Sanitation', 'Water Leakage', 'Water pipe leakage', 'high');

INSERT INTO issues (issue_category, issue_name, description, priority) VALUES
('Waste Management', 'Garbage Collection', 'Irregular garbage collection', 'medium');

INSERT INTO issues (issue_category, issue_name, description, priority) VALUES
('Public Safety', 'Security Concern', 'Public safety issues', 'urgent');

COMMIT;