-- LocalFix Database Schema for Job Status
-- Save as: database/migrations/004_create_job_status_table.sql

CREATE TABLE job_status (
    status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR2(50) UNIQUE NOT NULL,
    description VARCHAR2(200),
    sort_order NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert job status types in order
INSERT INTO job_status (status_name, description, sort_order) VALUES
('open', 'Job is posted and accepting applications', 1);

INSERT INTO job_status (status_name, description, sort_order) VALUES
('assigned', 'Worker has been assigned to the job', 2);

INSERT INTO job_status (status_name, description, sort_order) VALUES
('in_progress', 'Worker is currently working on the job', 3);

INSERT INTO job_status (status_name, description, sort_order) VALUES
('completed', 'Job has been completed by worker', 4);

INSERT INTO job_status (status_name, description, sort_order) VALUES
('verified', 'Job completion has been verified by admin', 5);

INSERT INTO job_status (status_name, description, sort_order) VALUES
('closed', 'Job is fully closed and payment processed', 6);

INSERT INTO job_status (status_name, description, sort_order) VALUES
('cancelled', 'Job was cancelled', 7);

COMMIT;