CREATE TABLE issues (
    issue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    citizen_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description CLOB NOT NULL,
    category VARCHAR2(100) NOT NULL,
    priority VARCHAR2(10) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    location_id NUMBER NOT NULL,
    image_url VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'submitted' CHECK (status IN ('submitted', 'assigned', 'in_progress', 'resolved', 'closed')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraints
    CONSTRAINT fk_issues_citizen FOREIGN KEY (citizen_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_issues_location FOREIGN KEY (location_id) REFERENCES locations(location_id)
);

-- Indexes for better performance
CREATE INDEX idx_issues_citizen ON issues(citizen_id);
CREATE INDEX idx_issues_location ON issues(location_id);
CREATE INDEX idx_issues_status ON issues(status);
CREATE INDEX idx_issues_category ON issues(category);

-- Trigger for auto-updating updated_at
CREATE OR REPLACE TRIGGER trg_issues_updated_at
    BEFORE UPDATE ON issues
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/