-- LocalFix Database Schema for Application Status
-- Save as: database/migrations/006_create_application_status_table.sql

CREATE TABLE application_status (
    status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR2(50) UNIQUE NOT NULL,
    description VARCHAR2(200),
    sort_order NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert application status types
INSERT INTO application_status (status_name, description, sort_order) VALUES
('submitted', 'Application has been submitted by worker', 1);

INSERT INTO application_status (status_name, description, sort_order) VALUES
('under_review', 'Application is being reviewed by citizen/admin', 2);

INSERT INTO application_status (status_name, description, sort_order) VALUES
('accepted', 'Application has been accepted', 3);

INSERT INTO application_status (status_name, description, sort_order) VALUES
('rejected', 'Application has been rejected', 4);

INSERT INTO application_status (status_name, description, sort_order) VALUES
('withdrawn', 'Application was withdrawn by worker', 5);

COMMIT;