-- Withdrawals table for worker payouts
-- Save as: database/migrations/019_create_withdrawals_table.sql

CREATE TABLE withdrawals (
    withdrawal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id NUMBER NOT NULL,
    method VARCHAR2(30) NOT NULL CHECK (method IN ('bkash','nagad','rocket','sonali_bank')),
    account_number VARCHAR2(50) NOT NULL,
    amount NUMBER(10,2) NOT NULL CHECK (amount > 0),
    status VARCHAR2(20) DEFAULT 'processing' CHECK (status IN ('processing','successful','failed')),
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    transaction_id VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_withdrawals_worker FOREIGN KEY (worker_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX idx_withdrawals_worker ON withdrawals(worker_id);
CREATE INDEX idx_withdrawals_status ON withdrawals(status);
CREATE INDEX idx_withdrawals_requested ON withdrawals(requested_at);

CREATE OR REPLACE TRIGGER trg_withdrawals_updated_at
    BEFORE UPDATE ON withdrawals
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

COMMIT;
