-- LocalFix Database Schema for Ratings
-- Save as: database/migrations/010_create_ratings_table.sql

CREATE TABLE ratings (
    rating_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id NUMBER NOT NULL,
    citizen_id NUMBER NOT NULL,
    worker_id NUMBER NOT NULL,
    rating NUMBER(2,1) NOT NULL,
    review_comment CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraints
    CONSTRAINT fk_ratings_job FOREIGN KEY (job_id) REFERENCES jobs(job_id) ON DELETE CASCADE,
    CONSTRAINT fk_ratings_citizen FOREIGN KEY (citizen_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_ratings_worker FOREIGN KEY (worker_id) REFERENCES users(user_id) ON DELETE CASCADE,
    
    -- Check constraints
    CONSTRAINT chk_ratings_rating CHECK (rating >= 1 AND rating <= 5),
    
    -- Ensure only one rating per job
    CONSTRAINT uk_ratings_job UNIQUE (job_id)
);

-- Indexes
CREATE INDEX idx_ratings_job ON ratings(job_id);
CREATE INDEX idx_ratings_citizen ON ratings(citizen_id);
CREATE INDEX idx_ratings_worker ON ratings(worker_id);
CREATE INDEX idx_ratings_rating ON ratings(rating);

COMMIT;