-- LocalFix Database Schema for Worker Skills
-- Save as: database/migrations/012_create_worker_skills_table.sql

CREATE TABLE worker_skills (
    skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id NUMBER NOT NULL,
    skill_name VARCHAR2(100) NOT NULL,
    experience_level VARCHAR2(20) DEFAULT 'beginner' CHECK (experience_level IN ('beginner', 'intermediate', 'advanced', 'expert')),
    years_experience NUMBER(2) DEFAULT 0,
    is_verified NUMBER(1) DEFAULT 0 CHECK (is_verified IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraints
    CONSTRAINT fk_worker_skills_worker FOREIGN KEY (worker_id) REFERENCES users(user_id) ON DELETE CASCADE,
    
    -- Check constraints
    CONSTRAINT chk_worker_skills_years CHECK (years_experience >= 0 AND years_experience <= 50),
    
    -- Unique constraint to prevent duplicate skills per worker
    CONSTRAINT uk_worker_skills UNIQUE (worker_id, skill_name)
);

-- Indexes
CREATE INDEX idx_worker_skills_worker ON worker_skills(worker_id);
CREATE INDEX idx_worker_skills_name ON worker_skills(skill_name);
CREATE INDEX idx_worker_skills_level ON worker_skills(experience_level);

-- Insert common skills for testing
INSERT INTO worker_skills (worker_id, skill_name, experience_level, years_experience) 
SELECT user_id, 'Electrical Work', 'intermediate', 3 FROM users WHERE user_type = 'worker' AND ROWNUM = 1;

INSERT INTO worker_skills (worker_id, skill_name, experience_level, years_experience) 
SELECT user_id, 'Plumbing', 'advanced', 5 FROM users WHERE user_type = 'worker' AND ROWNUM = 1;

COMMIT;